# Generated by Django 6.0.4 on 2026-04-11 19:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Licenciatura",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("apresentacao", models.TextField()),
                ("competencias", models.TextField()),
                ("ects", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="UnidadeCurricular",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("ano", models.IntegerField()),
                ("semestre", models.CharField(max_length=20)),
                ("ects", models.IntegerField()),
                (
                    "imagem",
                    models.ImageField(blank=True, null=True, upload_to="cadeiras/"),
                ),
                ("link", models.URLField(blank=True, max_length=300, null=True)),
                (
                    "licenciatura",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="unidades_curriculares",
                        to="portfolio.licenciatura",
                    ),
                ),
            ],
        ),
    ]
