# Generated by Django 6.0.5 on 2026-05-18 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0002_competencia_docente_formacao_makingof_tecnologia_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="docente",
            name="nome",
            field=models.CharField(max_length=1000),
        ),
    ]
